In [1]:
import os

In [3]:
import sys
sys.version


'3.10.18 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:08:55) [MSC v.1929 64 bit (AMD64)]'

In [4]:
import numpy as np

In [6]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [2]:
import tensorflow as tf

In [6]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [4]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 105608200712134448
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3795845120
locality {
  bus_id: 1
  links {
  }
}
incarnation: 12437182977469469584
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]


In [7]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

# Or more simply:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17201086081700972748
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3795845120
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7462878295071570971
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [8]:
print("TensorFlow version:", tf.__version__)
print("GPU devices:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.10.0
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
import cv2

In [9]:
python --version

NameError: name 'python' is not defined

In [21]:
!pip install opencv-python

  Using cached opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl.metadata (19 kB)
Using cached opencv_python-4.12.0.88-cp37-abi3-win_amd64.whl (39.0 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/12.9 MB 9.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.9 MB 7.1 MB/s eta 0:00:02
   ------------- -------------------------- 4.5/12.9 MB 6.9 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.9 MB 6.6 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.9 MB 6.4 MB/s eta 0:00:01
   ------------------------ --------------- 7.9/12.9 MB 6.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.9 MB 6.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.9 MB 6.4 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.9 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 6.2 MB/s eta 0:00:01
   ---

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 2.2.6 which is incompatible.


In [4]:
categories = ['without_mask','with_mask']


In [5]:
data = []
for category in categories:
    path = os.path.join('data',category)
    label = categories.index(category)
    for file in os.listdir(path):
        img_path = os.path.join(path,file)
        img = cv2.imread(img_path)
        img = cv2.resize(img,(224,224))
        data.append([img,label])

In [6]:
import random

In [11]:
random.shuffle(data)

In [7]:
X = []
y = []

for features,label in data:
    X.append(features)
    y.append(label)

In [9]:
import numpy as np

In [10]:
X = np.array(X)
y = np.array(y)

In [12]:
X = X/255

In [11]:
X = X[:2000]
y = y[:2000]

In [13]:
X.shape

(2000, 224, 224, 3)

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [15]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [16]:
y_train = y_train.astype('int32')   # or int32 if classification
y_test = y_test.astype('int32')

In [17]:
from tensorflow.keras.applications.vgg16 import VGG16

In [18]:
vgg = VGG16()

In [23]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [19]:
from tensorflow.keras.models import Sequential

In [20]:
model = Sequential()

In [21]:
for layer in vgg.layers[:-1]:
    model.add(layer)

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [22]:
for layer in model.layers:
    layer.trainable = False

In [23]:
from tensorflow.keras.layers import Dense

In [24]:
model.add(Dense(1,activation='sigmoid'))

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [25]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [50]:
X_small = X_train[:500]
y_small = y_train[:500]

In [ ]:
# train_ds = tf.data.Dataset.from_tensor_slices((X_train, y_train)).shuffle(1000).batch(32).prefetch(tf.data.AUTOTUNE)
# test_ds = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(32)

model.fit(X_train,y_train,batch_size = 1 ,validation_data=(X_test,y_test), epochs=5)


Epoch 1/5


In [49]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13083853989504596868
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3795845120
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7928158982340711856
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]


In [45]:
print(type(X_train), X_train.dtype, X_train.shape)
print(type(y_train), y_train.dtype, y_train.shape)

<class 'numpy.ndarray'> float32 (5000, 224, 224, 3)
<class 'numpy.ndarray'> float32 (5000,)


In [46]:
print(X_train[0])

[[[0.33333334 0.45490196 0.6313726 ]
  [0.31764707 0.41960785 0.6       ]
  [0.3529412  0.4392157  0.60784316]
  ...
  [0.7176471  0.78431374 0.77254903]
  [0.74509805 0.8117647  0.7921569 ]
  [0.7647059  0.83137256 0.79607844]]

 [[0.33333334 0.44705883 0.62352943]
  [0.3254902  0.41568628 0.6039216 ]
  [0.35686275 0.43529412 0.6117647 ]
  ...
  [0.7490196  0.8117647  0.8       ]
  [0.77254903 0.8392157  0.8235294 ]
  [0.78039217 0.8352941  0.8235294 ]]

 [[0.33333334 0.44705883 0.62352943]
  [0.33333334 0.42352942 0.6039216 ]
  [0.37254903 0.44705883 0.61960787]
  ...
  [0.7490196  0.81960785 0.8117647 ]
  [0.7607843  0.84313726 0.83137256]
  [0.76862746 0.8392157  0.827451  ]]

 ...

 [[0.93333334 0.93333334 0.9490196 ]
  [0.9098039  0.8901961  0.9098039 ]
  [0.3647059  0.24705882 0.28627452]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[0.9372549  0.93333334 0.9490196 ]
  [0.83137256 0.80784315 0.827451  ]


In [47]:
y_train = y_train.astype('int32')
y_test = y_test.astype('int32')

